name: VoiceNotes
options:
  bundleIdPrefix: com.notesagent
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

targets:
  VoiceNotes:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - VoiceNotes
      - ../shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notesagent.voicenotes
        PRODUCT_NAME: VoiceNotes
        INFOPLIST_FILE: VoiceNotes/Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1"  # iPhone only
        SUPPORTS_MACCATALYST: NO
      debug:
        CODE_SIGN_IDENTITY: "Apple Development"
      release:
        CODE_SIGN_IDENTITY: "iPhone Distribution"
    scheme:
      build:
        targets:
          VoiceNotes: all
      run:
        commandLineArguments:
        environmentVariables:
      test:
        commandLineArguments:
        environmentVariables:
